### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by qqxx6661** [Gao-Chuan/encrypt_netdisk#1]
Hi, I'd like to use the Attribute based Crypto in your code but cannot find the correct way to use it.

**Comment by 1phan** [comment]
Oh I'm sorry. I have not completed the first version of the code. Actually, I find it's too disk-consuming when I finished the first part of the demo, and I don't know such an app could be useful or not...so I canceled it...

**Comment by 1phan** [comment]
诶，中国人啊，
我写到一半觉得我用的这个cpabe方案出来的那个属性树太占内存了，作为一个加密网盘来说似乎有些代价太大，就半路中止了……

**Comment by qqxx6661** [comment]
哈哈，知道了。我找找属性加密的实现方案的，有什么比较经典的属性加密项目推荐吗？能跑起来的就行。

**Comment by 1phan** [comment]
我写这个项目时谷歌搜到过一个伯克利大学官网的开源cpabe项目，你可以搜搜看~

**Comment by qqxx6661** [comment]
好的，谢谢
